import pyautogui
import time

time.sleep(1)

password="xxxxxxx"

pyautogui.press("win")
pyautogui.write("google chrome")
pyautogui.press("enter")
time.sleep(3)
pyautogui.write("https://www.instagram.com")
pyautogui.press("enter")
time.sleep(3)
pyautogui.moveTo(1223,620,2)
pyautogui.click()
pyautogui.moveTo(935,380,2)
pyautogui.click()
pyautogui.write("xxxxxxxxx") 
pyautogui.keyDown("altright")
pyautogui.write("q")
pyautogui.keyUp("altright")
time.sleep(2)
pyautogui.write("gmail.com")
pyautogui.press("tab")
pyautogui.write("XXXXXXXXX")      
pyautogui.press("tab")
pyautogui.write("XXXXXXXXX")
time.sleep(1)
pyautogui.press("tab")
pyautogui.press("tab")
time.sleep(2)
pyautogui.write(password)
time.sleep(2)
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("enter")
time.sleep(2)
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.moveTo(959,415,1)
pyautogui.click()
pyautogui.moveTo(953,584,1)
pyautogui.click()
pyautogui.moveTo(1028,416,1)
pyautogui.click()
pyautogui.moveTo(1017,593,1)
pyautogui.scroll(-200)
time.sleep(2)
pyautogui.click()
time.sleep(1)
pyautogui.press("tab")
pyautogui.press("enter")
pyautogui.click(275,12)
time.sleep(2)
pyautogui.write("https://mail.google.com/mail/u/2/?ogbl#inbox")
pyautogui.press("enter")
time.sleep(2)
pyautogui.click(75,386)
time.sleep(2)
pyautogui.click(107,522)
time.sleep(2)
pyautogui.click(473,255)
time.sleep(2)
pyautogui.click(1067,952)
